#!/usr/bin/env python3
"""Emit a valid Godot 4 project.godot with a complete input map."""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# physical keycodes (Godot 4 Key enum)
KEY = {
    "W": 87, "A": 65, "S": 83, "D": 68, "E": 69, "F": 70, "Q": 81, "R": 82,
    "C": 67, "V": 86, "G": 71, "H": 72, "T": 84, "1": 49, "2": 50, "3": 51,
    "SHIFT": 4194325, "CTRL": 4194326, "ALT": 4194327, "ESC": 4194305,
    "TAB": 4194306, "SPACE": 32, "ENTER": 4194309,
}


def key_event(name):
    code = KEY[name]
    return ('Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"",'
            '"device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,'
            '"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,'
            f'"physical_keycode":{code},"key_label":0,"unicode":0,"location":0,'
            '"echo":false,"script":null)')


def mouse_button_event(button_index):
    return ('Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"",'
            f'"device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,'
            '"ctrl_pressed":false,"meta_pressed":false,"button_mask":0,"factor":1.0,'
            f'"button_index":{button_index},"canceled":false,"pressed":false,"double_click":false,'
            '"script":null)')


ACTIONS = {
    "move_forward": ["W"],
    "move_back": ["S"],
    "move_left": ["A"],
    "move_right": ["D"],
    "sprint": ["SHIFT"],
    "crouch": ["CTRL", "C"],
    "interact": ["E"],
    "flashlight": ["F"],
    "night_vision": ["V"],
    "lean_left": ["Q"],
    "lean_right": ["R"],
    "pause": ["ESC"],
    "inventory": ["TAB"],
    "slot_1": ["1"],
    "slot_2": ["2"],
    "walk_slow": ["ALT"],
    "zoom": ["MB2"],
}

lines = []
lines.append('; Engine configuration file.')
lines.append('; Generated by tools/gen_project_godot.py -- DO NOT EDIT BY HAND if unsure.')
lines.append('')
lines.append('config_version=5')
lines.append('')
lines.append('[application]')
lines.append('')
lines.append('config/name="BACKROOMS // BODYCAM"')
lines.append('config/description="Survival horror in a custom Level 0 map (GLB). Bodycam found-footage presentation."')
lines.append('run/main_scene="res://scenes/main.tscn"')
lines.append('config/features=PackedStringArray("4.4", "Forward Plus")')
lines.append('config/icon="res://icon.png"')
lines.append('')
lines.append('[autoload]')
lines.append('')
lines.append('GameSettings="*res://scripts/autoload/game_settings.gd"')
lines.append('AudioBank="*res://scripts/autoload/audio_bank.gd"')
lines.append('Net="*res://scripts/autoload/net.gd"')
lines.append('')
lines.append('[debug]')
lines.append('')
lines.append('gdscript/warnings/unsafe_property_access=0')
lines.append('gdscript/warnings/unsafe_method_access=0')
lines.append('gdscript/warnings/unsafe_cast=0')
lines.append('gdscript/warnings/unsafe_call_argument=0')
lines.append('gdscript/warnings/untyped_declaration=0')
lines.append('gdscript/warnings/inferred_declaration=0')
lines.append('')
lines.append('[display]')
lines.append('')
lines.append('window/size/viewport_width=1280')
lines.append('window/size/viewport_height=720')
lines.append('window/stretch/mode="canvas_items"')
lines.append('window/stretch/aspect="expand"')
lines.append('window/handheld/orientation=4')          # sensor landscape
lines.append('window/dpi/allow_hidpi=true')
lines.append('window/size/mode.mobile=3')            # fullscreen on phones
lines.append('')
lines.append('[filesystem]')
lines.append('')
lines.append('import/blender/enabled=false')
lines.append('')
lines.append('[gui]')
lines.append('')
lines.append('theme/default_font_multichannel_signed_distance_field=true')
lines.append('')
lines.append('[input]')
lines.append('')
for action, keys in ACTIONS.items():
    events = []
    for k in keys:
        if k.startswith("MB"):
            events.append(mouse_button_event(int(k[2:])))
        else:
            events.append(key_event(k))
    lines.append(f'{action}={{')
    lines.append('"deadzone": 0.2,')
    lines.append('"events": [' + ", ".join(events))
    lines.append(']')
    lines.append('}')
lines.append('')
lines.append('[internationalization]')
lines.append('')
lines.append('locale/translations=PackedStringArray()')
lines.append('')
lines.append('[rendering]')
lines.append('')
lines.append('renderer/rendering_method="forward_plus"')
lines.append('renderer/rendering_method.mobile="mobile"')
# old GPUs (no Vulkan, D3D12 without SM6) -> skip the D3D12 attempt, go straight to OpenGL3
lines.append('rendering_device/driver.windows="vulkan"')
lines.append('rendering_device/fallback_to_d3d12=false')
lines.append('rendering_device/fallback_to_vulkan=true')
lines.append('rendering_device/fallback_to_opengl3=true')
lines.append('anti_aliasing/quality/msaa_3d=0')        # the graphics preset sets AA at runtime
lines.append('anti_aliasing/quality/screen_space_aa=0')
lines.append('textures/vram_compression/import_etc2_astc=true')
lines.append('textures/vram_compression/import_s3tc_bptc=true')
lines.append('lights_and_shadows/positional_shadow/atlas_size.mobile=2048')
lines.append('lights_and_shadows/positional_shadow/soft_shadow_filter_quality.mobile=0')
lines.append('shading/overrides/force_vertex_shading.mobile=false')
lines.append('environment/glow/upscale_mode.mobile=0')
lines.append('scaling_3d/mode=0')
lines.append('mesh_lod/lod_change/threshold_pixels.mobile=4.0')
lines.append('')
lines.append('[physics]')
lines.append('')
lines.append('common/physics_ticks_per_second=60')
lines.append('3d/physics_engine="GodotPhysics3D"')
lines.append('')
lines.append('[audio]')
lines.append('')
lines.append('driver/output_latency.mobile=40')
lines.append('environment/defaults/default_clear_color=Color(0.01, 0.01, 0.012, 1)')
lines.append('')

with open(os.path.join(ROOT, "project.godot"), "w") as f:
    f.write("\n".join(lines))
print("project.godot written:", len(lines), "lines")
